---
- name: Initial Provision
  hosts: all
  become: true

  tasks:
    
    - name: Install aptitude using apt
      apt: name=aptitude state=latest force_apt_get=yes

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
        state: present

    - name: Install Docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose && ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      ignore_errors: yes
      
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      
  handlers:

    - name: restart docker
      service:
        name: docker
        state: restarted

